### ISSUE TITLE
Failed to load content

### ISSUE THREAD

**Issue by RoderickQiu** [memset0/oi-archive-vue-frontend#1]
Just found that you've been working on this new proj and I checked it out with Firefox 80 and found that the loading circle keeps rotating around, with this information shown in Console:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://raw.githubusercontent.com/memset0/oi-archive-old-source/master/codevs/index.json. (Reason: CORS request did not succeed).

**Comment by RoderickQiu** [comment]
![image](https://user-images.githubusercontent.com/42290260/94263331-75b91680-ff67-11ea-926f-0dcdae488411.png)

**Comment by RoderickQiu** [comment]
Oh I found that after connecting to vpn it was fixed - just the problem that raw.githubusercontent.com being blocked from mainland, China so the JSON was not fetched. Long time no use and forgot about this problem!

But still, it's not so nice for most - cuz many people don't have access to vpn.

**Comment by memset0** [comment]
因为那个 [仓库](https://github.com/memset0/oi-archive-old-source) 的大小 > 50mb 没法走 jsdelivr 的 cdn，就只能用 raw.githubusercontent.com，国内部分地区访问不了。

仓库很大的主要原因是因为有图片，现在我还没想好图片等等数据怎么存所以还咕着。（想着 json 数据薅 jsdelivr，图片薅国内的一些服务，两者分开存）

因为本身作为一个 archive 项目，想着能够比较方便的备份和部署，所以没有整后端的打算，存数据也全部薅的资本主义羊毛，就暂时凑活凑活。

**Comment by scris** [comment]
可以考虑下 https://raw.now.sh/
